apiVersion: v1
kind: PersistentVolume
metadata:
  name: dgraph-vol
  labels:
    app: dgraph
spec:
  storageClassName: "2020569a-65b2-4a5a-b256-ebf54980a048"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/dgraph
